version: '3.8'
services:
  jenkins:
    image: hxandy/custom-jenkins-for-local:latest
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    ports:
      - "9090:8080"
      - "51000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
  docker:
    image: docker:dind
    privileged: true
    container_name: jenkins-docker
    restart: unless-stopped
    ports:
      - "2376:2376"
    networks:
      jenkins: 
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-home:/var/jenkins_home
volumes:
  jenkins-home:
  jenkins-docker-certs:

networks:
  jenkins: